FROM python:3.8.3
WORKDIR /app

COPY backend ./
RUN pip install flask flask_cors spacy python-dotenv pymongo huggingface_hub spacy-transformers
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "base:app"]